CREATE TABLE task_state
(
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR                     NOT NULL,
    left_task_state_id  BIGINT UNIQUE DEFERRABLE REFERENCES task_state (id) ON UPDATE CASCADE ON DELETE CASCADE,
    right_task_state_id BIGINT UNIQUE DEFERRABLE REFERENCES task_state (id) ON UPDATE CASCADE ON DELETE CASCADE,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    project_id          BIGINT                      NOT NULL REFERENCES project (id)
);
