CREATE TABLE project
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR                     NOT NULL UNIQUE,
    creator_email VARCHAR                     NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
